#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-intel-gmmlib-soname1
Version  : 18.3.0
Release  : 2
URL      : https://github.com/intel/gmmlib/archive/intel-gmmlib-18.3.0.tar.gz
Source0  : https://github.com/intel/gmmlib/archive/intel-gmmlib-18.3.0.tar.gz
Summary  : Intel(R) Graphics Memory Management Library
Group    : Development/Tools
License  : MIT
Requires: compat-intel-gmmlib-soname1-lib = %{version}-%{release}
Requires: compat-intel-gmmlib-soname1-license = %{version}-%{release}
BuildRequires : buildreq-cmake

%description
Intel(R) Graphics Memory Management Library
*******************************************

%package dev
Summary: dev components for the compat-intel-gmmlib-soname1 package.
Group: Development
Requires: compat-intel-gmmlib-soname1-lib = %{version}-%{release}
Provides: compat-intel-gmmlib-soname1-devel = %{version}-%{release}

%description dev
dev components for the compat-intel-gmmlib-soname1 package.


%package lib
Summary: lib components for the compat-intel-gmmlib-soname1 package.
Group: Libraries
Requires: compat-intel-gmmlib-soname1-license = %{version}-%{release}

%description lib
lib components for the compat-intel-gmmlib-soname1 package.


%package license
Summary: license components for the compat-intel-gmmlib-soname1 package.
Group: Default

%description license
license components for the compat-intel-gmmlib-soname1 package.


%prep
%setup -q -n gmmlib-intel-gmmlib-18.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1544711480
mkdir -p clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1544711480
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-intel-gmmlib-soname1
cp LICENSE.md %{buildroot}/usr/share/package-licenses/compat-intel-gmmlib-soname1/LICENSE.md
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
%exclude /usr/include/igdgmm/GmmLib/CachePolicy/GmmCachePolicyConditionals.h
%exclude /usr/include/igdgmm/GmmLib/CachePolicy/GmmCachePolicyResourceUsageDefinitions.h
%exclude /usr/include/igdgmm/GmmLib/CachePolicy/GmmCachePolicyUndefineConditionals.h
%exclude /usr/include/igdgmm/GmmLib/CachePolicy/GmmGen10CachePolicy.h
%exclude /usr/include/igdgmm/GmmLib/CachePolicy/GmmGen11CachePolicy.h
%exclude /usr/include/igdgmm/GmmLib/CachePolicy/GmmGen8CachePolicy.h
%exclude /usr/include/igdgmm/GmmLib/CachePolicy/GmmGen9CachePolicy.h
%exclude /usr/include/igdgmm/GmmLib/Platform/GmmPlatforms.h
%exclude /usr/include/igdgmm/GmmLib/Texture/GmmTexture.h
%exclude /usr/include/igdgmm/GmmLib/Utility/CpuSwizzleBlt/CpuSwizzleBlt.c
%exclude /usr/include/igdgmm/GmmLib/Utility/CpuSwizzleBlt/assert.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/GmmLog.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/async_logger.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/common.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/details/async_log_helper.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/details/async_logger_impl.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/details/file_helper.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/details/format.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/details/line_logger_fwd.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/details/line_logger_impl.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/details/log_msg.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/details/logger_impl.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/details/mpmc_bounded_q.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/details/null_mutex.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/details/os.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/details/pattern_formatter_impl.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/details/registry.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/details/spdlog_impl.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/fmt/bundled/format.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/fmt/bundled/ostream.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/fmt/bundled/printf.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/fmt/fmt.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/fmt/ostr.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/formatter.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/logger.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/sinks/android_sink.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/sinks/ansicolor_sink.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/sinks/base_sink.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/sinks/dist_sink.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/sinks/file_sinks.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/sinks/msvc_sink.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/sinks/null_sink.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/sinks/ostream_sink.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/sinks/sink.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/sinks/stdout_sinks.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/sinks/syslog_sink.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/sinks/wincolor_sink.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/spdlog.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmLog/spdlog/tweakme.h
%exclude /usr/include/igdgmm/GmmLib/Utility/GmmUtility.h
%exclude /usr/include/igdgmm/GmmLib/inc/External/Common/CachePolicy/GmmCachePolicyGen10.h
%exclude /usr/include/igdgmm/GmmLib/inc/External/Common/CachePolicy/GmmCachePolicyGen11.h
%exclude /usr/include/igdgmm/GmmLib/inc/External/Common/CachePolicy/GmmCachePolicyGen8.h
%exclude /usr/include/igdgmm/GmmLib/inc/External/Common/CachePolicy/GmmCachePolicyGen9.h
%exclude /usr/include/igdgmm/GmmLib/inc/External/Common/GmmCachePolicy.h
%exclude /usr/include/igdgmm/GmmLib/inc/External/Common/GmmCachePolicyCommon.h
%exclude /usr/include/igdgmm/GmmLib/inc/External/Common/GmmCachePolicyExt.h
%exclude /usr/include/igdgmm/GmmLib/inc/External/Common/GmmClientContext.h
%exclude /usr/include/igdgmm/GmmLib/inc/External/Common/GmmCommonExt.h
%exclude /usr/include/igdgmm/GmmLib/inc/External/Common/GmmConst.h
%exclude /usr/include/igdgmm/GmmLib/inc/External/Common/GmmDebug.h
%exclude /usr/include/igdgmm/GmmLib/inc/External/Common/GmmFormatTable.h
%exclude /usr/include/igdgmm/GmmLib/inc/External/Common/GmmGttExt.h
%exclude /usr/include/igdgmm/GmmLib/inc/External/Common/GmmInfo.h
%exclude /usr/include/igdgmm/GmmLib/inc/External/Common/GmmInfoExt.h
%exclude /usr/include/igdgmm/GmmLib/inc/External/Common/GmmInternal.h
%exclude /usr/include/igdgmm/GmmLib/inc/External/Common/GmmLibDll.h
%exclude /usr/include/igdgmm/GmmLib/inc/External/Common/GmmLibDllName.h
%exclude /usr/include/igdgmm/GmmLib/inc/External/Common/GmmMemAllocator.hpp
%exclude /usr/include/igdgmm/GmmLib/inc/External/Common/GmmPlatformExt.h
%exclude /usr/include/igdgmm/GmmLib/inc/External/Common/GmmProto.h
%exclude /usr/include/igdgmm/GmmLib/inc/External/Common/GmmResourceFlags.h
%exclude /usr/include/igdgmm/GmmLib/inc/External/Common/GmmResourceInfo.h
%exclude /usr/include/igdgmm/GmmLib/inc/External/Common/GmmResourceInfoCommon.h
%exclude /usr/include/igdgmm/GmmLib/inc/External/Common/GmmResourceInfoExt.h
%exclude /usr/include/igdgmm/GmmLib/inc/External/Common/GmmTextureExt.h
%exclude /usr/include/igdgmm/GmmLib/inc/External/Common/GmmUtil.h
%exclude /usr/include/igdgmm/GmmLib/inc/External/Linux/GmmResourceInfoLin.h
%exclude /usr/include/igdgmm/GmmLib/inc/GmmLib.h
%exclude /usr/include/igdgmm/igdgmm.h
%exclude /usr/include/igdgmm/inc/common/gfxmacro.h
%exclude /usr/include/igdgmm/inc/common/gfxplatform.h
%exclude /usr/include/igdgmm/inc/common/gtsysinfo.h
%exclude /usr/include/igdgmm/inc/common/igfxfmid.h
%exclude /usr/include/igdgmm/inc/common/sku_wa.h
%exclude /usr/include/igdgmm/inc/portable_compiler.h
%exclude /usr/include/igdgmm/inc/umKmInc/UmKmDmaPerfTimer.h
%exclude /usr/include/igdgmm/inc/umKmInc/UmKmEnum.h
%exclude /usr/include/igdgmm/inc/umKmInc/sharedata.h
%exclude /usr/include/igdgmm/util/g_gfxDebug.h
%exclude /usr/include/igdgmm/util/gfxDebug.h
%exclude /usr/lib64/libigdgmm.so
%exclude /usr/lib64/pkgconfig/igdgmm.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libigdgmm.so.1
/usr/lib64/libigdgmm.so.1.0.0

%files license
%defattr(0644,root,root,0755)
%exclude /usr/share/package-licenses/compat-intel-gmmlib-soname1/LICENSE.md
